name: Alert rules check
description: Execute simple bin for checking given alert rules
author: preved911
inputs:
  path:
    description: Path to proccess.
    default: .
  subcommand:
    description: Which template format should be used.
    default: kustomize
  rule_type:
    description: Which rule type should be used.
    default: VMRule
runs:
  using: docker
  image: docker://sputniksystemsorg/alertrules-checker:v0.0.2
  entrypoint: /checker
  args:
    - ${{ inputs.subcommand }}
    - --rule-type=${{ inputs.rule_type }}
    - ${{ inputs.path }}
